spring:
  datasource:
#    username: postgres
#    password: root
    url: jdbc:sqlite::resource:database.db
    driver-class-name: org.sqlite.JDBC
  mvc:
    view:
      suffix: .html
      prefix: templates/
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB

mybatis:
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    edu.hubu.xiaomishop: debug
